# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘kiqit’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kiqit
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'kiqitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target ‘kiqitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end
